version: '2'

services:

 stamper:
  container_name: stamper
  image: cismet/stamper:latest
  network_mode: bridge
  ports:
   - 8082:10010
  volumes:
   - ./config/stamper.json:/app/config/stamper.json:ro
   - ./config/private.key:/app/config/private.key:ro
   - ./config/public.key:/app/config/public.key:ro
   - ./data:/app/data
  restart: always
  command: swagger project start
